version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: opentelemetry-jaeger
    versions:
    - 0.12.0
  - dependency-name: opentelemetry
    versions:
    - 0.13.0
  - dependency-name: tokio-test
    versions:
    - 0.4.0
  - dependency-name: matchers
    versions:
    - 0.1.0
  - dependency-name: hyper
    versions:
    - 0.14.2
  - dependency-name: tower
    versions:
    - 0.4.1
  - dependency-name: bytes
    versions:
    - 1.0.0
